spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/postgres?currentSchema=public'
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect